# Generated by Django 6.0.7 on 2026-08-02 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Dislalia, TDL, Disfemia, Afasia, TEA, Síndrome genético...', max_length=200)),
                ('area_afectada', models.CharField(choices=[('habla', 'Habla'), ('lenguaje', 'Lenguaje'), ('comunicacion', 'Comunicación'), ('deglucion', 'Deglución')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('habla', 'Habla'), ('lenguaje', 'Lenguaje'), ('comunicacion', 'Comunicación'), ('deglucion', 'Deglución')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('dificultad', models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=1)),
                ('edad_minima', models.PositiveSmallIntegerField(default=0)),
                ('edad_maxima', models.PositiveSmallIntegerField(default=99)),
            ],
            options={
                'ordering': ['area', 'dificultad'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='goals.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('objetivos', models.ManyToManyField(related_name='planes', to='goals.objetivo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='goals.paciente')),
            ],
        ),
    ]
